#!/usr/bin/env bash
set -euo pipefail

# --- Config ---
APP_DIR="/opt/axentx/social-assembly"
ENV_FILE="${APP_DIR}/.env"
SECRETS_FILE="/run/axentx/secrets.env"  # tmpfs for ephemeral secrets
ADMIN_CREATED_FLAG="${APP_DIR}/.admin_created"
HEALTH_ENDPOINT="http://localhost:8080/health"
MAX_RETRIES=30
RETRY_DELAY=1

# Ensure /run/axentx exists and is secure
mkdir -p /run/axentx
chmod 750 /run/axentx

# Skip if already run
if [[ -f "${ADMIN_CREATED_FLAG}" ]]; then
  echo "Admin already created. Skipping init."
  exit 0
fi

# --- Generate .env ---
if [[ ! -f "${ENV_FILE}" ]]; then
  echo "Generating .env file..."
  cat > "${ENV_FILE}" <<EOF
# Auto-generated by init_wizard.sh
AXENTX_SECRET_KEY=$(openssl rand -hex 32)
AXENTX_JWT_SECRET=$(openssl rand -hex 32)
AXENTX_DB_PASSWORD=$(openssl rand -hex 16)
AXENTX_DB_ROOT_PASSWORD=$(openssl rand -hex 16)
AXENTX_REDIS_PASSWORD=$(openssl rand -hex 16)
AXENTX_ADMIN_EMAIL=${AXENTX_ADMIN_EMAIL:-admin@axentx.local}
AXENTX_ADMIN_USERNAME=${AXENTX_ADMIN_USERNAME:-axentx-admin}
AXENTX_ADMIN_PASSWORD=${AXENTX_ADMIN_PASSWORD:-$(openssl rand -hex 16)}
AXENTX_HOST=localhost
AXENTX_PORT=8080
AXENTX_DB_HOST=db
AXENTX_DB_PORT=5432
AXENTX_REDIS_HOST=redis
AXENTX_REDIS_PORT=6379
EOF
  chmod 600 "${ENV_FILE}"
fi

# --- Write ephemeral secrets ---
cat > "${SECRETS_FILE}" <<EOF
AXENTX_ADMIN_PASSWORD=$(grep AXENTX_ADMIN_PASSWORD "${ENV_FILE}" | cut -d= -f2)
AXENTX_DB_PASSWORD=$(grep AXENTX_DB_PASSWORD "${ENV_FILE}" | cut -d= -f2)
AXENTX_REDIS_PASSWORD=$(grep AXENTX_REDIS_PASSWORD "${ENV_FILE}" | cut -d= -f2)
EOF
chmod 600 "${SECRETS_FILE}"

# --- Wait for app health ---
echo "Waiting for application to be ready..."
for ((i=1; i<=MAX_RETRIES; i++)); do
  if curl -fs "${HEALTH_ENDPOINT}" >/dev/null 2>&1; then
    echo "Application is ready."
    break
  fi
  if [[ $i -eq MAX_RETRIES ]]; then
    echo "ERROR: Application did not become ready within ${MAX_RETRIES} seconds."
    exit 1
  fi
  sleep "${RETRY_DELAY}"
done

# --- Create admin user ---
if ! command -v python3 &> /dev/null; then
  echo "ERROR: python3 not found. Cannot create admin user."
  exit 1
fi

if ! python3 "${APP_DIR}/scripts/create_admin.py" \
  --email "${AXENTX_ADMIN_EMAIL}" \
  --username "${AXENTX_ADMIN_USERNAME}" \
  --password "${AXENTX_ADMIN_PASSWORD}"; then
  echo "WARNING: Admin user creation may have failed or already exists."
fi

# --- Mark completion ---
touch "${ADMIN_CREATED_FLAG}"
echo "First-run setup complete. Admin credentials written to ${ENV_FILE}"